name: Command.plugin
version: '${project.version}'
main: linker.command.plugin.Command.Main
api-version: 1.18
authors: [ Linker ]
description: Command Plugin for Skyblock
commands:
  display:
    description: Display Command.
  msg:
    description: Msg command
  r:
    description: Reply command
