name: Command.plugin
version: '${project.version}'
main: linker.command.plugin.Command.Main
api-version: 1.18
authors: [ Linker ]
description: Command Plugin for Skyblock
commands:
  discord:
    description: Link of Discord.
  b:
    description: Welcome command.
